#配置文件的加载顺序优先级:properties > yml > yaml
server:
  port: 8082
name: abc
#对象
person:
  name: zhangsan #${name} #zhangsan
  age: 20
  address:
    - beijing
    - shanghai
#对象行内写法
person2: {name: zhangsan,age: 20}
#数组
address:
  - beijing
  - shanghai
#数组行内写法
address2: [beijing,shanghai]
#纯量
msg1: 'hello \n world'  #不会识别转义字符
msg2: "hello \n world"  #会识别转义字符